### ISSUE TITLE
compose文件是不是應該這樣寫

### ISSUE THREAD

**Issue by MononeV** [Ghost-chu/PeerBanHelper#62]
```
services:
  peerbanhelper:
    image: "ghostchu/peerbanhelper:latest-native-linux"
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - ./:/app/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9898:9898"
    environment:
# 取消注释以使用 Native Image 本地二进制文件，占用资源更少，但可能有 BUG
#      - USE_NATIVE_IMAGE=1
```
